apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: manowar
  name: manowar
spec:
  replicas: 2
  selector:
    matchLabels:
      app: manowar
  template:
    metadata:
      labels:
        app: manowar
    spec:
      containers:
      - name: manowar
        image: vitortineo/manowar
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

