apiVersion: v1
kind: Service
metadata:
  name: mano-lb
  namespace: default
spec:
  selector:
    app: manowar
  ports:
    - protocol: TCP
      port: 80        # porta externa do service
      targetPort: 8080 # porta interna do container
  type: LoadBalancer
