name: CI-GitOps

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed                # so ser[a rxecutado qdo o primeiro workflow terminar

jobs:
  update-gitops:
    runs-on: ubuntu-latest
    steps:
      # Checkout direto do repo GitOps
      - name: Checkout GitOps repo
        uses: actions/checkout@v3
        with:
          repository: vi-tineo/ManowarK8sGitOps
          token: ${{ secrets.GITOPS_TOKEN }}
          path: gitops

      # Atualizar o manifesto com a nova tag da imagem
      - name: Update manifest
        run: |
          cd gitops/k8s
          sed -i "s|image: vitortineo/manowar:.*|image: vitortineo/manowar:${{ github.sha }}|" manoDeploy.yaml
          git config user.name "salazar"
          git config user.email "salazart@users.noreply.github.com"
          git commit -am "Update image to ${{ github.sha }}"
          git push
