name: CI-GitOps

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  update-gitops:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v3
        with:
          repository: vi-tineo/ManowarK8sGitOps
          token: ${{ secrets.GITOPS_TOKEN }}
          path: gitops

      - name: Update manifest
        run: |
          cd gitops/k8s
          sed -i "s|image: vitortineo/manowar:.*|image: vitortineo/manowar:${{ github.sha }}|" manoDeploy.yaml
          git config user.name "salazar"
          git config user.email "salazart@users.noreply.github.com"
          git add manoDeploy.yaml
          git commit -m "Update image to ${{ github.sha }}"
          git push
